version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop-rails_config
    versions:
    - 1.3.1
    - 1.3.2
    - 1.4.0
    - 1.4.2
    - 1.5.1
  - dependency-name: rails
    versions:
    - 6.1.2.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
